### ISSUE TITLE
请教有没有可以确定社区数量的社区发现算法

### ISSUE THREAD

**Issue by BaiqiLi123** [xmweijh/CommunityDetection#2]
博主你好，首先十分感谢你的开源代码，让我学习了很多。
我现在在做一篇论文的实验，其中数据集需要使用社区发现算法处理，我希望能准确指出具体的社区分割数量，尤其是在重叠社区这一领域。请问你是否知道有没有可以指明社区数量的社区发现算法（重叠和非重叠）？
十分感谢

**Comment by xmweijh** [comment]
你的意思是已知社区数量了吗？那这种方法特别多。比如(UCoDe: Unified Community Detection with Graph Convolutional Networks、(J-NEC)Unsupervised Learning of Joint Embeddings for Node Representation and Community Detection)都是可以应用在重叠社区与非重叠社区上。

**Comment by BaiqiLi123** [comment]
我希望能够指定社区发现的输出社区数量。具体场景：我有一个graph的数据集，希望将它处理成20个社区，并且最好社区与社区之间有部分重叠节点，所以需要能事先固定输出的社区数量。
   非常感谢你的帮助，我去找一下相关论文和开源代码！

**Comment by xmweijh** [comment]
> 我希望能够指定社区发现的输出社区数量。具体场景：我有一个graph的数据集，希望将它处理成20个社区，并且最好社区与社区之间有部分重叠节点，所以需要能事先固定输出的社区数量。 非常感谢你的帮助，我去找一下相关论文和开源代码！

我上面提到的两片论文就可以实现重叠社区，而且代码都是开源的

**Comment by BaiqiLi123** [comment]
十分感谢，祝你科研一切顺利！！！

**Comment by BaiqiLi123** [comment]
我还没有找到合适的方法，请问有没有一些较为经典的重叠节点社区的检测算法呢？函数调用中可以指明社区数量的。

**Comment by xmweijh** [comment]
> 我还没有找到合适的方法，请问有没有一些较为经典的重叠节点社区的检测算法呢？函数调用中可以指明社区数量的。

比较经典的话就BigCLAM《Overlapping Community Detection at Scale: A Nonnegative Matrix Factorization Approach》吧，或者基于深度学习的NOCD《Overlapping Community Detection with Graph Neural Networks》

**Comment by LBJgigigi** [comment]
想求教这个louvain算法的整个流程讲解，我需要对其进行改进，有偿求教，微信号LBJgigigi13
