### ISSUE TITLE
你好！请教问题，copra算法有问题

### ISSUE THREAD

**Issue by BaiqiLi123** [xmweijh/CommunityDetection#5]
你好！请教问题，copra算法有问题

![image](https://user-images.githubusercontent.com/47620706/222154456-2e77f0c0-d2db-4f74-a6c4-c64bedcc51e5.png)
copra算法这一步报错了。
报错信息如下：我感觉报错信息时“使用random.sample时，字典为空，无法选取”
![image](https://user-images.githubusercontent.com/47620706/222155125-21c5d992-2009-4614-a42b-a77218ee62b6.png)

怎么改呢？

**Comment by xmweijh** [comment]
> random.sample

temp_label有问题吧，你可以debug下看下具体细节

**Comment by BaiqiLi123** [comment]
len（temp_label.keys（））= 0
这个怎么处理捏？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月2日(周四) 上午8:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xmweijh/CommunityDetection] 你好！请教问题，copra算法有问题 (Issue #5)




  
random.sample
  
temp_label有问题吧，你可以debug下看下具体细节

**Comment by xmweijh** [comment]
> temp_label.

debug看下他为什么为0
